print("გიორგი ლაშქარაშვილი")
print("hello world")
print("sigma")
print("tuff")
print("chad")
print("nika jelo")
print("gabu")
print("gabuN2")
print("ბატონი გიორგი ბოყოველი")
print("Davit Shavidze")
print("ბატონი დავით გრძელიშვილი")
print("GOA")
print("is")
print("best")
print("bad boy")
print("good boy")
print("spider man")
print("roblox")
print("obama")
print("trump")
print("dota2")

